// DragonOS Lucide Icon Map
import type { ReactNode } from 'react';
import {
  LayoutDashboard,
  Clock,
  FileText,
  Calendar,
  CheckSquare,
  Target,
  RefreshCw,
  Columns3,
  Terminal,
  Calculator,
  Timer,
  Settings,
  BookOpen,
  DollarSign,
  Smile,
  Lock,
  Palette,
  Layers,
  Keyboard,
  Trophy,
  Activity,
  Headphones,
  Globe,
  Languages,
  CloudSun,
  ClipboardList,
  Zap,
  FileCode,
  Search,
  Moon,
  MoonStar,
  Power,
} from 'lucide-react';

const iconSize = { size: 20 };
const iconSizeLg = { size: 24 };

export const appIcons: Record<string, ReactNode> = {
  dashboard:     <LayoutDashboard {...iconSize} />,
  clock:         <Clock {...iconSize} />,
  notepad:       <FileText {...iconSize} />,
  calendar:      <Calendar {...iconSize} />,
  todo:          <CheckSquare {...iconSize} />,
  goals:         <Target {...iconSize} />,
  habits:        <RefreshCw {...iconSize} />,
  kanban:        <Columns3 {...iconSize} />,
  terminal:      <Terminal {...iconSize} />,
  calculator:    <Calculator {...iconSize} />,
  pomodoro:      <Timer {...iconSize} />,
  settings:      <Settings {...iconSize} />,
  journal:       <BookOpen {...iconSize} />,
  expenses:      <DollarSign {...iconSize} />,
  mood:          <Smile {...iconSize} />,
  vault:         <Lock {...iconSize} />,
  doodle:        <Palette {...iconSize} />,
  flashcards:    <Layers {...iconSize} />,
  typingtest:    <Keyboard {...iconSize} />,
  achievements:  <Trophy {...iconSize} />,
  systemmonitor: <Activity {...iconSize} />,
  focussounds:   <Headphones {...iconSize} />,
  browser:       <Globe {...iconSize} />,
  translator:    <Languages {...iconSize} />,
  weather:       <CloudSun {...iconSize} />,
  clipboard:     <ClipboardList {...iconSize} />,
  quicknotes:    <Zap {...iconSize} />,
  markdown:      <FileCode {...iconSize} />,
};

// Large variant for landing / desktop icons
export const appIconsLg: Record<string, ReactNode> = {
  dashboard:     <LayoutDashboard {...iconSizeLg} />,
  clock:         <Clock {...iconSizeLg} />,
  notepad:       <FileText {...iconSizeLg} />,
  calendar:      <Calendar {...iconSizeLg} />,
  todo:          <CheckSquare {...iconSizeLg} />,
  goals:         <Target {...iconSizeLg} />,
  habits:        <RefreshCw {...iconSizeLg} />,
  kanban:        <Columns3 {...iconSizeLg} />,
  terminal:      <Terminal {...iconSizeLg} />,
  calculator:    <Calculator {...iconSizeLg} />,
  pomodoro:      <Timer {...iconSizeLg} />,
  settings:      <Settings {...iconSizeLg} />,
  journal:       <BookOpen {...iconSizeLg} />,
  expenses:      <DollarSign {...iconSizeLg} />,
  mood:          <Smile {...iconSizeLg} />,
  vault:         <Lock {...iconSizeLg} />,
  doodle:        <Palette {...iconSizeLg} />,
  flashcards:    <Layers {...iconSizeLg} />,
  typingtest:    <Keyboard {...iconSizeLg} />,
  achievements:  <Trophy {...iconSizeLg} />,
  systemmonitor: <Activity {...iconSizeLg} />,
  focussounds:   <Headphones {...iconSizeLg} />,
  browser:       <Globe {...iconSizeLg} />,
  translator:    <Languages {...iconSizeLg} />,
  weather:       <CloudSun {...iconSizeLg} />,
  clipboard:     <ClipboardList {...iconSizeLg} />,
  quicknotes:    <Zap {...iconSizeLg} />,
  markdown:      <FileCode {...iconSizeLg} />,
};

// Small variant for command palette, search
export const appIconsSm: Record<string, ReactNode> = {
  dashboard:     <LayoutDashboard size={16} />,
  clock:         <Clock size={16} />,
  notepad:       <FileText size={16} />,
  calendar:      <Calendar size={16} />,
  todo:          <CheckSquare size={16} />,
  goals:         <Target size={16} />,
  habits:        <RefreshCw size={16} />,
  kanban:        <Columns3 size={16} />,
  terminal:      <Terminal size={16} />,
  calculator:    <Calculator size={16} />,
  pomodoro:      <Timer size={16} />,
  settings:      <Settings size={16} />,
  journal:       <BookOpen size={16} />,
  expenses:      <DollarSign size={16} />,
  mood:          <Smile size={16} />,
  vault:         <Lock size={16} />,
  doodle:        <Palette size={16} />,
  flashcards:    <Layers size={16} />,
  typingtest:    <Keyboard size={16} />,
  achievements:  <Trophy size={16} />,
  systemmonitor: <Activity size={16} />,
  focussounds:   <Headphones size={16} />,
  browser:       <Globe size={16} />,
  translator:    <Languages size={16} />,
  weather:       <CloudSun size={16} />,
  clipboard:     <ClipboardList size={16} />,
  quicknotes:    <Zap size={16} />,
  markdown:      <FileCode size={16} />,
};

export { Search, Moon, MoonStar, Power };
